In [2]:
import numpy as np
import pandas as pd
from scipy.stats import chisquare
from scipy.stats import chi2_contingency 

### 두 모비율에 대한 비교

### 모비율 비교를 위한 검정 (표본 크기가 클때)
- - -
- 검정통계량 : $Z=\frac{\hat{p_1}-\hat{p_2}}{\sqrt{\hat{p}(1-\hat{p})(\frac{1}{n_1}+\frac{1}{n_2})}} \approx N(0, 1) \; under \; H_0$

```java
public class BootSpringBootApplication {
    public static void main(String[] args) {
        System.out.println("Hello, Man!")
    }
}
```

In [4]:
support = pd.read_excel("support.xlsx")

In [17]:
supportTable = pd.crosstab(index=support["Gender"], 
                           columns=support["YesNo"])
supportTable

YesNo    No  Yes
Gender          
Female   96  104
Male    140  110

In [18]:
pd.crosstab(index=support["Gender"], 
            columns=support["YesNo"], 
            normalize='index')

YesNo     No   Yes
Gender            
Female  0.48  0.52
Male    0.56  0.44

### 범주형 자료에 대한 여러 모집단의 비교

In [8]:
Pea = np.array([315, 108, 101, 32])
P0 = np.array([9/16, 3/16, 3/16, 1/16])*np.sum(Pea)
print(P0) # 기대빈도 출력

[312.75 104.25 104.25  34.75]


In [10]:
chisquare(Pea, P0)

Power_divergenceResult(statistic=0.4700239808153477, pvalue=0.925425895103616)

In [11]:
x = np.array([[73, 98, 79],[82,58,110]])
table = pd.DataFrame(x, ['Male', 'Female'],['Kor', 'Math', 'Eng'])
print(table)

        Kor  Math  Eng
Male     73    98   79
Female   82    58  110


In [14]:
# 동질성 검정 : 카이제곱 검정

chi2_contingency(table)
chi2, pval, df, expected = chi2_contingency(table)

print("Chi2 =",chi2) # 카이제곱 통계량 출력
print("p-value =",pval) # p-값 출력
print("df =",df) # 자유도 출력
print("Expected value =",expected) # 기대빈도 출력

Chi2 = 15.863646986227634
p-value = 0.00035913094268842237
df = 2
Expected value = [[77.5 78.  94.5]
 [77.5 78.  94.5]]


In [5]:
survey = pd.read_table("survey.txt", sep = " ")
# 분할표 작성
y = survey.groupby(['Smoke','Exer']).size()
# table = y.unstack() # Producing Dataframe from Series of multiindex 
print(y.unstack())

Exer   Freq  None  Some
Smoke                  
Heavy     7     1     3
Never    87    18    84
Occas    12     3     4
Regul     9     1     7


In [16]:
chi2_contingency(table)
chi2, pval, df, expected = chi2_contingency(table)

print("Chi-squared test: X-squared = %s,p-value = %s, df = %s, expected value = %s"\
 % (round(chi2,5),round(pval,5),df, expected))


Chi-squared test: X-squared = 5.48855,p-value = 0.48284, df = 6, expected value = [[ 5.36016949  1.0720339   4.56779661]
 [92.09745763 18.41949153 78.48305085]
 [ 9.25847458  1.85169492  7.88983051]
 [ 8.28389831  1.65677966  7.05932203]]
